project:
  name: ftl-flask-demo
  domain: ftl.example.com
  email: ftl@example.com

servers:
  - host: 127.0.0.1
    port: 22
    user: ftl
    ssh_key: ~/.ssh/id_rsa

services:
  - name: flask-app
    port: 5000
    health_check:
      path: /tasks
      interval: 10s
      timeout: 5s
      retries: 3
    routes:
      - path: /
        strip_prefix: false
    env:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-ftl_db}
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY}

dependencies:
  - name: postgres
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-ftl_db}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256

volumes:
  - postgres_data
